### ISSUE TITLE
SC

### ISSUE THREAD

**Issue by nunnally** [brandonasuncion/2D-Projectile-Motion-in-GunBound#1]
Maybe you can share some codes or news about this project?

**Comment by brandonasuncion** [comment]
Sorry, I haven't worked on this project in a while. The idea was to go over the mathematics involved in creating an aimbot for GunBound.

As of now, progress has been put on a halt, and I'm uncertain whether I'll continue working on it. Though if you have any specific questions, I may be able to answer them for you or point you in the right direction.

**Comment by nunnally** [comment]
Well, my objective is to make a gunbound BOT too, i already bypassed softnyx AC, but im having difficulty to get the maths behind mobiles shots.
Maybe trico is a parobola in the main bulltet, and a sen or cos function in the other 2 bullets ?

**Comment by brandonasuncion** [comment]
Yes, that's exactly how it works. A rough outline of the rotating bullets would be something like:
```
    x = radius * cos(angle + kt)
    y = radius * sin(angle + kt)
```
where `t = time`, `k = some coefficient`
You would just need to offset the x/y values by the center bullet's position to get the final (x, y) coordinate of the rotating bullets.

**Comment by nunnally** [comment]
Alright, thanks... And hmm, maybe u can share some part of codes? Thanks

**Comment by eduardomendes2** [comment]
> Well, my objective is to make a gunbound BOT too, i already bypassed softnyx AC, but im having difficulty to get the maths behind mobiles shots.
> Maybe trico is a parobola in the main bulltet, and a sen or cos function in the other 2 bullets ?

Can you help me with some code too? I'm still trying to get the addresses and only the shot angle I didn't find yet. Did you?

**Comment by brandonasuncion** [comment]
I haven't been able to find an address for shot angle — it's trickier than the other memory values. Reading the pixels on the screen would be the easiest method to get the value.

**Comment by nunnally** [comment]
I'm back to gunbound after few months. Well, seems like the shot angle is a random value, I'm trying to watch this address and see if a function that update it can give us the random value.

Also, how you get the coords? Can you share the general formula for most common mobiles?

**Comment by eduardomendes2** [comment]
I've found the angle. The value is encrypted. I had to hook the game by dll injection using assembly to get the decrypted value. I could reverse the whole decrypt function but I had no patience for this. The coords are very easy to get. Go to metamine map, stay in some regular horizontal floor and move horizontally searching for changed/unchanged value, 4 bytes. Vertical coords address is 4 bytes after. But this is only the beginning of the rabbit hole.

**Comment by coyotezin** [comment]
> I've found the angle. The value is encrypted. I had to hook the game by dll injection using assembly to get the decrypted value. I could reverse the whole decrypt function but I had no patience for this. The coords are very easy to get. Go to metamine map, stay in some regular horizontal floor and move horizontally searching for changed/unchanged value, 4 bytes. Vertical coords address is 4 bytes after. But this is only the beginning of the rabbit hole.

any chance you could share in detail your method to get the angle value? been struggling to get it and didnt really wanted to use reading pixels method, is there any way i could get in contact with you?
