### ISSUE TITLE
2d the simulation lines

### ISSUE THREAD

**Issue by tokiodeo** [brandonasuncion/2D-Projectile-Motion-in-GunBound#2]
hello that library uses to draw in 2d the simulation lines

**Comment by brandonasuncion** [comment]
The code I wrote was for DragonBound, which is a browser based clone of GunBound. Everything was written in JavaScript using an HTML5 canvas.

**Comment by jersonjcnt** [comment]
como obtienes

> El código que escribí fue para DragonBound, que es un clon de GunBound basado en el navegador. Todo fue escrito en JavaScript utilizando un lienzo HTML5.

**Comment by xBrunoMedeiros** [comment]
Will the formula still be published?

**Comment by xBrunoMedeiros** [comment]
Could you publish the code the way it is? I'm interessed in your formulas.
